### ISSUE TITLE
Evtl. Umbenennung in "Matomo Statistik" 

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/matomo#10]
Vorschlag:
In der Hauptnavigation das AddOn anstatt "Matomo" in "Matomo Statistik" umbenennen, um klarer zu machen, was Matomo ist, wenn man als Webseitenbetreiber nur selten in seinem Redaxo eingeloggt ist und nach diesen Statistiken sucht.

![Bildschirmfoto 2019-12-02 um 16 49 59](https://user-images.githubusercontent.com/16903055/69973435-cc122000-1523-11ea-9748-238e9d1d846f.png)

**Comment by skerbis** [comment]
Nur zu

**Comment by schuer** [comment]
Müsste eigentlich »Matomo-Statistik« sein, wenn man es genau nimmt. Mit Bindestrich. ;)

**Comment by danspringer** [comment]
Einverstanden :-)
