### ISSUE TITLE
Javascript Tag laden per API 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/matomo#3]
First Step: 
https://github.com/FriendsOfREDAXO/matomo/commit/9d7acdb2dd08f2bfd190f9020251a6465b63de4e

**Comment by alexplusde** [comment]
Auch DSGVO-Konform laden können wäre wichtig, für Matomo-Installationen die nicht auf dem lokalen Server sind.

**Comment by skerbis** [comment]
Es holt nur den Code per api ab - aktuell. Die erforderlichen Einstellungen müssen in matomo oder im Cookie consent addon durchgeführt werden.

**Comment by skerbis** [comment]
Zum Verständnis, der Trackingcode wird in diesem AddOn nicht automatisch eingebunden, sondern zur weiteren Bearbeitung "nur" abgeholt.

**Comment by skerbis** [comment]
@alexplusde magst Du dich dran trauen und den Code über den API-Call generieren?
