### ISSUE TITLE
Tracking-Code-Generator anbieten

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/matomo#5]
Mit Hilfe der API den Tracking-Code mit gewünschten Optionen generieren können. 

Aktuell wird nur ein Default-Tracking-Code von Matomo geladen. 
In matomo selbst lässt sich dieser allerdings konfigurieren. Die API bietet entsprechende Funktionen an. 

Ich würde hier gerne zumindest gerne eine Auswahl anbieten um den Code generieren zu können. 

@alexplusde hast Du Lust?

**Comment by skerbis** [comment]
Die möglichen Optionen: 

- **SitesManager.getJavascriptTag** (idSite, piwikUrl = '', mergeSubdomains = '', groupPageTitlesByDomain = '', mergeAliasUrls = '', visitorCustomVariables = '', pageCustomVariables = '', customCampaignNameQueryParam = '', customCampaignKeywordParam = '', doNotTrack = '', disableCookies = '', trackNoScript = '', crossDomain = '', forceMatomoEndpoint = '')

**Comment by alexplusde** [comment]
Gerade nicht, habe noch keine Notwendigkeit bisher für das Adodon

**Comment by skerbis** [comment]
ok ... ich werde Optionen für folgendes anbieten: doNotTrack = '', disableCookies = '', trackNoScript = '', 
und ein Feld individuellen Code einbinden ...:-) Dann haben wir ja alles

**Comment by skerbis** [comment]
Optionen können ab 1.1.0 gesetzt werden.
